### ISSUE TITLE
These Hangar version don't work on Android 10 Samsung Note 10 plus.

### ISSUE THREAD

**Issue by paulpoco** [mimicmobile/hangar#2]
These Hangar version don't work on Android 10 Samsung Note 10 plus.  No widget to add, constantly closing.

Also on the regular Playstore version: it works but never seems to update the used apps.  So have to go into settings and place it again so the used apps get updated.

**Comment by corcoran** [comment]
@paulpoco there's no widget in this version of hangar. 

When you say closing, do you mean the Settings page when you load the app? Is it a crash?
